services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - '5000:5000'
        env_file:
            - ./backend/.env

